version: '3'

services:
  mstest-shp:
    image: mstest-shp:latest  # Define the image name
    container_name: mstest-shp-container  # Define the container name
    build: .
    environment:
      # SHOPIFY_FLAG_STORE: [Your Store URL]
      SHOPIFY_API_KEY: 363fdb0803ffd14f77e988d71ea3dac6
      SHOPIFY_API_SECRET: d8fbfe84129c0b73298a5e42e5c65c5a
      # API_SECRET_KEY: [Your API SECRET]
      SHOPIFY_APP_URL: http://3.7.254.10/3000
      # SHOPIFY_SCOPES: read_products,write_products
      SCOPES: read_products,write_products
    ports:
      - '3000:3000' # Port mapping
